### ISSUE TITLE
Clicking links not working?

### ISSUE THREAD

**Issue by irthomasthomas** [dark-eye/com.darkeye.chatGPT#9]
Hi, loving this widget! Just wondering, does clicking links in a chat not work? It's not working for me anyway. How can I debug a plasmoid? Like, can I run  it from a terminal to see log output?

**Comment by dark-eye** [comment]
@irthomasthomas In the last  version you can  enable the developer debug console by right clicking the plasmoid -> Advanced (Tab) -> "Show debug console".

After that  you`ll see a debug button at the  bottom  of the plasmoid.

But i assume that the issue is a qt/qml issue  probably  I fail to listen to  a regular  navigation events i`ll look into it...
